# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pFeature <- function(x, min_p = 1e-6) {
    .Call('_perich_pFeature', PACKAGE = 'perich', x, min_p)
}

pSample <- function(x, min_p = 1e-6) {
    .Call('_perich_pSample', PACKAGE = 'perich', x, min_p)
}

testVector <- function(x, f, background = NULL, weights = NULL, alternative = "both", n_iter = 1000L, laplace = 1, ci_type = "bca", ci_level = 0.95) {
    .Call('_perich_testVector', PACKAGE = 'perich', x, f, background, weights, alternative, n_iter, laplace, ci_type, ci_level)
}

testMatrix <- function(x, f, background = NULL, weights = NULL, alternative = "both", n_iter = 1000L, laplace = 1, ci_type = "bca", ci_level = 0.95) {
    .Call('_perich_testMatrix', PACKAGE = 'perich', x, f, background, weights, alternative, n_iter, laplace, ci_type, ci_level)
}

Quantile <- function(x, probs) {
    .Call('_perich_Quantile', PACKAGE = 'perich', x, probs)
}

perCI <- function(theta, conf_level = 0.95) {
    .Call('_perich_perCI', PACKAGE = 'perich', theta, conf_level)
}

BCA <- function(theta, conf_level = 0.95) {
    .Call('_perich_BCA', PACKAGE = 'perich', theta, conf_level)
}

